contractor-app/config/routes.rb
Rails.application.routes.draw do
  root 'payment_requests#index'

  resources :payment_requests, only: %i[index new create destroy]
end

contractor-app/app/models/payment_request.rb
# frozen_string_literal: true

class PaymentRequest < ApplicationRecord
  enum :status, { pending: 0, accepted: 1, rejected: 2 }

  validates_presence_of :amount_in_cents, :currency
  validates :currency, inclusion: { in: Currencies::ALLOWED_CURRENCIES }

  def amount
    amount_in_cents / 100.00
  end
end

contractor-app/app/controllers/payment_requests_controller.rb
# frozen_string_literal: true

class PaymentRequestsController < ApplicationController
  def index
    @payment_requests = PaymentRequest.all
  end

  def new
    @payment_request = PaymentRequest.new
  end

  def create
    result = ::PaymentRequests::Create.new(payment_request_params.to_h).call

    if result.success?
      flash[:notice] = result.success
    else
      flash[:alert] = result.failure
    end

    redirect_to payment_requests_path
  end

  def destroy
    result = ::PaymentRequests::Destroy.new(params.require(:id)).call

    if result.success?
      flash[:notice] = result.success
    else
      flash[:alert] = result.failure
    end

    redirect_to payment_requests_path
  end

  private

  def payment_request_params
    params.require(:payment_request).permit(:amount_in_cents, :currency, :description)
  end
end

contractor-app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ContractorApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% flash.each do |type, msg| %>
      <div>
        <%= msg %>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>

contractor-app/app/views/payment_requests/index.html.erb
<%= link_to 'Create new payment request', new_payment_request_path %>

<h2>Your payment requests</h2>

<table class="table">
  <tr>
    <th>Created at</th>
    <th>Amount</th>
    <th>Currency</th>
    <th>Description</th>
    <th>Status</th>
    <th>Actions</th>
  </tr>

  <% @payment_requests.each do |request| %>
    <tr>
      <td><%= request.created_at.to_s %><td>
      <td><%= number_with_precision(request.amount, precision: 2) %><td>
      <td><%= request.currency %><td>
      <td><%= request.description %><td>
      <td><%= request.status %><td>
      <td>
        <%= button_to 'Delete', payment_request_path(request), method: :delete, data: { confirm: 'Are you sure?' } %>
      </td>
    </tr>
  <% end %>
</table>

contractor-app/app/views/payment_requests/new.html.erb
<h2>New payment request</h2>

<%= form_with model: @payment_request do |f| %>
  <%= f.label :amount_in_cents, 'Amount in cents' %>
  <%= f.number_field :amount_in_cents, step: 1.0 %>

  <%= f.label :currency, 'Currency' %>
  <%= f.select :currency, options_for_select(Currencies::ALLOWED_CURRENCIES) %>

  <%= f.label :description, 'Description' %>
  <%= f.text_area :description %>

  <%= f.submit 'Create '%>
<% end %>